k3s_version: "latest"

k3s_server_url: "https://{{ hostvars['server1'].ansible_host }}:6443"
## TODO Add to ansible_vault file
k3s_token: "K10af8c5cdfca0e2f851c17b1d3f5cb89f6b89e00fe2ea49595970f3d0640ca1a98::server:65a6680f8a16f5d0e329e2f3486378ce"
   
k3s_agent_extra_args: "--node-external-ip {{ ansible_host }} --node-label role=worker  --with-node-id {{ ansible_host }}"