k3s_version: "latest"

k3s_server_url: "https://{{ hostvars['server1'].ansible_host }}:6443"
## TODO Add to ansible_vault file
k3s_token: "K104b990f6c90d4225fcb6dddb3e8e10e95f47ece3b2df95ca6b4391a38d34301fd::server:155de94730a70490962b9b81ffdc26bd"
   
k3s_agent_extra_args: "--node-external-ip {{ ansible_host }} --node-label role=worker  --with-node-id {{ ansible_host }}"