k3s_version: "latest"

k3s_server_url: "https://{{ hostvars['server1'].ansible_host }}:6443"
## TODO Add to ansible_vault file
k3s_token: "K10de431c917a0d6e10eb4d10a495b64f5c516a77a4c14ad66cd5a04d546689ec63::server:13b38ed5429ff7c56697b5cb3f7e50ac"
   
k3s_agent_extra_args: "--node-external-ip {{ ansible_host }} --node-label role=worker  --with-node-id {{ ansible_host }}"