k3s_version: "latest"

k3s_server_url: "https://{{ hostvars['server1'].ansible_host }}:6443"
## TODO Add to ansible_vault file
k3s_token: "K10a19139ff1ddb6d3f2c58691fa81e47c7bac0ce44b63bd4d3677a1a22e921a343::server:6704491c6925e48cc759ec6c92616614"
   
k3s_agent_extra_args: "--node-external-ip {{ ansible_host }} --node-label role=worker  --with-node-id {{ ansible_host }}"