all:
  children:
    k3s_servers:
      hosts:
        server1:
          ansible_host: 172.17.0.65 # Set to 127.0.0.1 if you are running the stack locally.
    k3s_workers:
      hosts:
        worker1:
           ansible_host: 172.17.0.78

