all:
  children:
    k3s_servers:
      hosts:
        server1:
           ansible_host: 127.0.0.1 # Set to LAN IP if you are not running locally or if u want to add worker nodes.
    k3s_workers:
      hosts:
        worker1:
           ansible_host: 1.2.3.4

