all:
  children:
    k3s_servers:
      hosts:
        server1:
          ansible_host: 127.0.0.1 # Set to host IP if you are not running locally.
    k3s_workers:
      hosts:
        worker1:
           ansible_host: 1.2.3.4

