all:
  children:
    k3s_servers:
      hosts:
        server1:
           ansible_host: 1.2.3.4 # Set the LAN server IP
    k3s_workers:
      hosts:
        worker1:
           ansible_host: 5.6.7.8 # Set the LAN worker IP

