---

- name: Apply app deployment
  become: yes
  kubernetes.core.k8s:
    state: present
    src: ../../k3s/app.yaml

- name: Apply ingress
  kubernetes.core.k8s:
    state: present
    src: ../../k3s/ingress.yaml

- name: Apply ingress service
  kubernetes.core.k8s:
    state: present
    src: ../../k3s/service.yaml
